### ISSUE TITLE
PDF output for flag war visualisation script

### ISSUE THREAD

**Issue by pibara-utopian** [pibara-utopian/asyncsteem#16]
@dhimmel: " It was a bit hard to search the figure to find my username. Have you considered exporting the detailed image as a PDF so we could search the text or even better using an interactive network layout?"

https://steemit.com/stats/@pibarabot/flag-war-stats-for-posts-made-on-2018-06-13

**Comment by dhimmel** [comment]
Does this python library create the network layout?

If so, can you point me to where? Possibly I could look into the enhancement.

**Comment by pibara-utopian** [comment]
moved from png to svg with an extra link to pdf.

**Comment by dhimmel** [comment]
Nice. Refs https://github.com/pibara-utopian/asyncsteem/commit/a7b0b935806790560a0f5119c4163e570e4a38cf.

Will future flag war posts be at https://steemit.com/@pibara? I'm excited to see the new output
